### ISSUE TITLE
Installing SRO using CLI also installs NodeFeatureDiscovery

### ISSUE THREAD

**Issue by kquinn1204** [openshift/special-resource-operator#102]
Following the procedure outlined in the docs `https://docs.openshift.com/container-platform/4.9/hardware_enablement/psap-special-resource-operator.html#installing-the-special-resource-operator-using-cli_special-resource-operator`. I installed the SRO Operator using the CLI. Contrary to what it states in docs and in the README associated with this repo there should be a pre-req to install the NFD. Is that a mistake as it appears to be installed when SRO is installed.

**Comment by ybettan** [comment]
Hi @kquinn1204.

If I am not mistaken, the link you supplied is the equivalent of installing SRO via the web console, which means SRO is installed via OLM.

OLM can handle operators dependencies, therefore, you get NFD for free.
When installing manually (using GH instructions), there is no one that handle those dependencies for you so you are the one responsible to install NFD.

So, AFAIK, there is no error in the doc, those are just 2 different types of installations.

Hope that is helping.

**Comment by bthurber** [comment]
@ybettan I believe the issue @kquinn1204 was hitting is that regardless of using the CLI or UI to install SRO, it deployed NFD automatically in each case.  The docs state that the install of NFD via CLI is a pre-req.  https://deploy-preview-41437--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator.html#installing-the-special-resource-operator-using-cli_special-resource-operator

I believe we need to create a PR to fix this.

**Comment by kquinn1204** [comment]
Yes that is indeed @ybettan the case as @bthurber has described. Either we call out as prereq or we automatically install when we install SRO.

**Comment by ybettan** [comment]
Sorry for the confusion the, I was referring to the doc in the [README.md](https://github.com/openshift/special-resource-operator#installation) - if installed directly from github, NFD should be installed manually before SRO.

Otherwise, it shouldn't so we should probably update the [doc](https://deploy-preview-41437--osdocs.netlify.app/openshift-enterprise/latest/hardware_enablement/psap-special-resource-operator.html#installing-the-special-resource-operator-using-cli_special-resource-operator) as @bthurber said.

Here is a [PR](https://github.com/openshift/special-resource-operator/pull/140) to be more precise regarding installing from Github.

**Comment by bthurber** [comment]
This dependency has been removed in the 4.11 release.  

https://github.com/openshift/special-resource-operator/pull/100
